// Generated by gencpp from file servecommunicate/mydataRequest.msg
// DO NOT EDIT!


#ifndef SERVECOMMUNICATE_MESSAGE_MYDATAREQUEST_H
#define SERVECOMMUNICATE_MESSAGE_MYDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servecommunicate
{
template <class ContainerAllocator>
struct mydataRequest_
{
  typedef mydataRequest_<ContainerAllocator> Type;

  mydataRequest_()
    : num1(0)
    , num2(0)  {
    }
  mydataRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::servecommunicate::mydataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servecommunicate::mydataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mydataRequest_

typedef ::servecommunicate::mydataRequest_<std::allocator<void> > mydataRequest;

typedef boost::shared_ptr< ::servecommunicate::mydataRequest > mydataRequestPtr;
typedef boost::shared_ptr< ::servecommunicate::mydataRequest const> mydataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servecommunicate::mydataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servecommunicate::mydataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servecommunicate::mydataRequest_<ContainerAllocator1> & lhs, const ::servecommunicate::mydataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servecommunicate::mydataRequest_<ContainerAllocator1> & lhs, const ::servecommunicate::mydataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servecommunicate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servecommunicate::mydataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servecommunicate::mydataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servecommunicate::mydataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servecommunicate::mydataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servecommunicate::mydataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servecommunicate::mydataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servecommunicate::mydataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::servecommunicate::mydataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::servecommunicate::mydataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servecommunicate/mydataRequest";
  }

  static const char* value(const ::servecommunicate::mydataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servecommunicate::mydataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# for calculate sum of two numbers\n"
"int32 num1\n"
"int32 num2\n"
;
  }

  static const char* value(const ::servecommunicate::mydataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servecommunicate::mydataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mydataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servecommunicate::mydataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servecommunicate::mydataRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVECOMMUNICATE_MESSAGE_MYDATAREQUEST_H
