// Generated by gencpp from file servecommunicate/mydataResponse.msg
// DO NOT EDIT!


#ifndef SERVECOMMUNICATE_MESSAGE_MYDATARESPONSE_H
#define SERVECOMMUNICATE_MESSAGE_MYDATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servecommunicate
{
template <class ContainerAllocator>
struct mydataResponse_
{
  typedef mydataResponse_<ContainerAllocator> Type;

  mydataResponse_()
    : sum(0)  {
    }
  mydataResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::servecommunicate::mydataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servecommunicate::mydataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mydataResponse_

typedef ::servecommunicate::mydataResponse_<std::allocator<void> > mydataResponse;

typedef boost::shared_ptr< ::servecommunicate::mydataResponse > mydataResponsePtr;
typedef boost::shared_ptr< ::servecommunicate::mydataResponse const> mydataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servecommunicate::mydataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servecommunicate::mydataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servecommunicate::mydataResponse_<ContainerAllocator1> & lhs, const ::servecommunicate::mydataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servecommunicate::mydataResponse_<ContainerAllocator1> & lhs, const ::servecommunicate::mydataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servecommunicate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servecommunicate::mydataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servecommunicate::mydataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servecommunicate::mydataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servecommunicate::mydataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servecommunicate::mydataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servecommunicate::mydataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servecommunicate::mydataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::servecommunicate::mydataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::servecommunicate::mydataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servecommunicate/mydataResponse";
  }

  static const char* value(const ::servecommunicate::mydataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servecommunicate::mydataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::servecommunicate::mydataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servecommunicate::mydataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mydataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servecommunicate::mydataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servecommunicate::mydataResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVECOMMUNICATE_MESSAGE_MYDATARESPONSE_H
